// Assemble mobile/www from the PWAs, injecting the backend URL for this build.
//
// The three PWAs stay the single source of truth — this copies them rather than forking, so
// a fix to the customer flow ships to web and Android from the same file. The only thing
// that differs is where the API lives, and that is injected here as `window.GM_API_BASE`
// (read by frontend/shared/config.js).
//
// Usage:
//   GM_API_BASE=http://192.168.1.42:8080 npm run build     # LAN device testing
//   GM_API_BASE=https://app.example.com  npm run build     # production
import { readdir, mkdir, copyFile, rm, writeFile, stat, readFile } from 'node:fs/promises';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, '..', 'frontend');
const OUT = join(here, 'www');

const API_BASE = (process.env.GM_API_BASE || '').replace(/\/+$/, '');

if (!API_BASE) {
  console.error(
    'GM_API_BASE is required.\n' +
      '  LAN testing : GM_API_BASE=http://<your-lan-ip>:8080 npm run build\n' +
      '  production  : GM_API_BASE=https://app.example.com npm run build\n\n' +
      'Without it the app would fall back to same-origin, which inside the WebView means the ' +
      'phone itself — every request would fail on launch.'
  );
  process.exit(1);
}

// A production build must not talk to a plaintext backend: the session token, the OTP code
// and every customer address would cross the network in the clear. Fail the build instead of
// shipping it — this is exactly the mistake that is invisible until it is a breach.
const isCleartext = API_BASE.startsWith('http://');
const isLocalHost = /^http:\/\/(localhost|127\.0\.0\.1|10\.|172\.(1[6-9]|2\d|3[01])\.|192\.168\.)/.test(API_BASE);
if (isCleartext && !isLocalHost) {
  console.error(`Refusing to build: ${API_BASE} is cleartext HTTP to a non-local address.`);
  process.exit(1);
}
if (isCleartext) {
  console.warn(`⚠  DEV BUILD — cleartext HTTP to ${API_BASE}. Never ship this to Play.`);
}

async function copyDir(from, to, skip = () => false) {
  await mkdir(to, { recursive: true });
  for (const entry of await readdir(from, { withFileTypes: true })) {
    const src = join(from, entry.name);
    if (skip(relative(SRC, src))) continue;
    const dst = join(to, entry.name);
    if (entry.isDirectory()) await copyDir(src, dst, skip);
    else await copyFile(src, dst);
  }
}

await rm(OUT, { recursive: true, force: true });

// The customer app is the root of the bundle; driver and operator sit under their paths so
// the landing page's role links keep working unchanged.
await copyDir(join(SRC, 'user'), OUT);
await copyDir(join(SRC, 'driver'), join(OUT, 'driver'));
await copyDir(join(SRC, 'operator'), join(OUT, 'operator'));
await copyDir(join(SRC, 'shared'), join(OUT, 'shared'));

// Service workers are web-only. Capacitor serves the bundle from the APK, and a registered
// SW would be a second, stale copy of the app competing with the real one.
for (const sw of ['sw.js', 'driver/sw.js', 'operator/sw.js']) {
  await rm(join(OUT, sw), { force: true });
}

// Inject the backend URL. Loaded BEFORE shared/config.js in every shell.
await writeFile(
  join(OUT, 'shared', 'env.js'),
  `// Generated by mobile/build-www.mjs — do not edit.\n` +
    `window.GM_API_BASE = ${JSON.stringify(API_BASE)};\n`
);

for (const page of ['index.html', 'driver/index.html', 'operator/index.html']) {
  const path = join(OUT, page);
  const depth = page.includes('/') ? '../' : '';
  let html = await readFile(path, 'utf8');
  // Rewrite absolute asset paths to relative ones: the WebView serves the bundle from the
  // app's own origin root, but keeping them relative makes the bundle position-independent.
  html = html.replace(
    '<script src="/shared/config.js"></script>',
    `<script src="/shared/env.js"></script>\n  <script src="/shared/config.js"></script>`
  );
  await writeFile(path, html);
  void depth;
}

const count = async (dir) => {
  let n = 0;
  for (const e of await readdir(dir, { withFileTypes: true })) {
    n += e.isDirectory() ? await count(join(dir, e.name)) : 1;
  }
  return n;
};
const bytes = async (dir) => {
  let total = 0;
  for (const e of await readdir(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    total += e.isDirectory() ? await bytes(p) : (await stat(p)).size;
  }
  return total;
};

console.log(`www built: ${await count(OUT)} files, ${Math.round((await bytes(OUT)) / 1024)} KB`);
console.log(`API base : ${API_BASE}`);
