// Generate the Android network-security config for THIS build's backend.
//
// Android blocks cleartext HTTP by default, which is correct — session tokens, login codes
// and customer addresses must never cross the network in the clear. But LAN device testing
// needs plain HTTP to a private IP (a self-signed cert is rejected by the WebView, and you
// can't get a Let's Encrypt cert for 192.168.x.x).
//
// So: cleartext is denied globally, then permitted ONLY for the exact private host this
// build targets. A production build produces a config with no exceptions at all — there is
// no flag anyone can forget to flip, because the permission is derived from the URL.
import { writeFile, mkdir, readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, 'android', 'app', 'src', 'main', 'res', 'xml');

const API_BASE = (process.env.GM_API_BASE || '').replace(/\/+$/, '');
if (!API_BASE) {
  console.error('GM_API_BASE is required (same value used for the www build).');
  process.exit(1);
}

const url = new URL(API_BASE);
const isCleartext = url.protocol === 'http:';
const PRIVATE_HOST =
  /^(localhost|127\.0\.0\.1|10\.\d+\.\d+\.\d+|192\.168\.\d+\.\d+|172\.(1[6-9]|2\d|3[01])\.\d+\.\d+)$/;

if (isCleartext && !PRIVATE_HOST.test(url.hostname)) {
  console.error(
    `Refusing: cleartext HTTP to ${url.hostname}, which is not a private address. ` +
      'Use HTTPS for anything reachable off your own network.'
  );
  process.exit(1);
}

const exception = isCleartext
  ? `
    <!-- DEV ONLY — generated for ${url.hostname}. A release build regenerates this file
         with no exceptions, because the host is derived from GM_API_BASE. -->
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">${url.hostname}</domain>
    </domain-config>
`
  : `
    <!-- Production build: no cleartext exceptions. -->
`;

const xml = `<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by mobile/configure-android.mjs — do not edit by hand.
     Regenerated from GM_API_BASE on every sync. -->
<network-security-config>
    <base-config cleartextTrafficPermitted="false">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
${exception}</network-security-config>
`;

await mkdir(OUT, { recursive: true });
await writeFile(join(OUT, 'network_security_config.xml'), xml);

// The WebView's own origin scheme has to match the backend's, or every request is blocked as
// mixed content before it leaves the phone — an `https://localhost` page cannot call
// `http://192.168.x.x`. Deriving it from the same URL keeps the two from disagreeing.
//
// `http://localhost` is still a SECURE CONTEXT by the localhost exception, so geolocation,
// crypto.randomUUID and the camera all keep working in dev builds.
const scheme = isCleartext ? 'http' : 'https';
const configPath = join(here, 'capacitor.config.json');
const config = JSON.parse(await readFile(configPath, 'utf8'));
config.server = { ...(config.server || {}), androidScheme: scheme };
await writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`);

console.log(
  isCleartext
    ? `network security: cleartext permitted for ${url.hostname} ONLY (dev build)`
    : 'network security: cleartext denied everywhere (release build)'
);
console.log(`app origin     : ${scheme}://localhost  (must be in the backend's CORS_ORIGINS)`);
